#!/bin/sh

set -e

bundle exec jekyll build
gem build jekyll-theme-hacker.gemspec

# Add the following line to ignore the LinkedIn link
bundle exec htmlproofer ./_site --url-ignore "https://www.linkedin.com/in/nolanhu"