#!/bin/sh

set -e

bundle exec jekyll build
gem build jekyll-theme-hacker.gemspec

# Add the following line to ignore the LinkedIn link
bundle exec htmlproofer ./_site --url-ignore "https://www.linkedin.com/in/nolanhu,https://linkedin.com/in/nolanhu,https://www.namecheap.com/support/api/,https://corporate.comcast.com/news-information/news-feed/comcast-and-nbcuniversal-drive-next-gen-storytelling-at-technology-hackathon,https://x402-ai-marketplace.vercel.app,http://morsecode.scphillips.com/translator.html,https://dev.nolanhu.com/blog/archive/backtrack-boot-2011/,https://dev.nolanhu.com/blog/archive/backtrack-installing-2011/,https://dev.nolanhu.com/blog/archive/firefox-addons-2011/,https://dev.nolanhu.com/blog/archive/router-security-2011/,https://dev.nolanhu.com/blog/archive/wep-hacking-2011/"